modLoader="javafml"
loaderVersion="[2,)"
license="MIT License"

[[mods]]
modId="creative_world"
version="0.2.4"
displayName="Creative world"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="300f20t, MCreator."
description="This is Release!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.creative_world]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creative_world]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"


[[dependencies.creative_world]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


[[mixins]]
    config="mixins.creative_world.json"