modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="creative_world"
version="0.2.3"
displayName="creative world"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="300f20t, MCreator."
description="This is Release!"

[[dependencies.creative_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




