/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.creativeworld.init;

import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.creativeworld.item.WirecuttersItem;
import net.mcreator.creativeworld.item.WashedcrushedtinoreItem;
import net.mcreator.creativeworld.item.WashedcrushedironoreItem;
import net.mcreator.creativeworld.item.WashedcrushedcopperoreItem;
import net.mcreator.creativeworld.item.TitanplateItem;
import net.mcreator.creativeworld.item.TitanSwordItem;
import net.mcreator.creativeworld.item.TitanShovelItem;
import net.mcreator.creativeworld.item.TitanPickaxeItem;
import net.mcreator.creativeworld.item.TitanIngotItem;
import net.mcreator.creativeworld.item.TitanHoeItem;
import net.mcreator.creativeworld.item.TitanAxeItem;
import net.mcreator.creativeworld.item.TitanArmorItem;
import net.mcreator.creativeworld.item.TinplateItem;
import net.mcreator.creativeworld.item.TinnuggetItem;
import net.mcreator.creativeworld.item.TincoverItem;
import net.mcreator.creativeworld.item.TinSwordItem;
import net.mcreator.creativeworld.item.TinShovelItem;
import net.mcreator.creativeworld.item.TinPickaxeItem;
import net.mcreator.creativeworld.item.TinIngotItem;
import net.mcreator.creativeworld.item.TinHoeItem;
import net.mcreator.creativeworld.item.TinAxeItem;
import net.mcreator.creativeworld.item.TinArmorItem;
import net.mcreator.creativeworld.item.ThecoreoftheformationItem;
import net.mcreator.creativeworld.item.ThecoreofmatterItem;
import net.mcreator.creativeworld.item.ThecoreofinvulnerabilityItem;
import net.mcreator.creativeworld.item.TapItem;
import net.mcreator.creativeworld.item.RubberItem;
import net.mcreator.creativeworld.item.ReelItem;
import net.mcreator.creativeworld.item.RawtitanItem;
import net.mcreator.creativeworld.item.RawtinItem;
import net.mcreator.creativeworld.item.ParticlebinderItem;
import net.mcreator.creativeworld.item.LatexItem;
import net.mcreator.creativeworld.item.KeycardItem;
import net.mcreator.creativeworld.item.IronwrenchItem;
import net.mcreator.creativeworld.item.IronplateItem;
import net.mcreator.creativeworld.item.IronhammerItem;
import net.mcreator.creativeworld.item.IronMortarItem;
import net.mcreator.creativeworld.item.EnergydetectorItem;
import net.mcreator.creativeworld.item.EndlesswatersourceItem;
import net.mcreator.creativeworld.item.ElectricjetpackItem;
import net.mcreator.creativeworld.item.ElectricalcircuitItem;
import net.mcreator.creativeworld.item.ElectricMotorItem;
import net.mcreator.creativeworld.item.DrillItem;
import net.mcreator.creativeworld.item.CrushedtinoreItem;
import net.mcreator.creativeworld.item.CrushedironoreItem;
import net.mcreator.creativeworld.item.CrushedcopperoreItem;
import net.mcreator.creativeworld.item.CreativiumnuggetItem;
import net.mcreator.creativeworld.item.CreativiumSwordItem;
import net.mcreator.creativeworld.item.CreativiumShovelItem;
import net.mcreator.creativeworld.item.CreativiumPickaxeItem;
import net.mcreator.creativeworld.item.CreativiumIngotItem;
import net.mcreator.creativeworld.item.CreativiumHoeItem;
import net.mcreator.creativeworld.item.CreativiumAxeItem;
import net.mcreator.creativeworld.item.CreativiumArmorItem;
import net.mcreator.creativeworld.item.CreativereelItem;
import net.mcreator.creativeworld.item.CreativemodItem;
import net.mcreator.creativeworld.item.CreativedrillItem;
import net.mcreator.creativeworld.item.CreativeElectricMotorItem;
import net.mcreator.creativeworld.item.CreatingcoreItem;
import net.mcreator.creativeworld.item.CopperplateItem;
import net.mcreator.creativeworld.item.CoppernuggetItem;
import net.mcreator.creativeworld.item.CopperSwordItem;
import net.mcreator.creativeworld.item.CopperShovelItem;
import net.mcreator.creativeworld.item.CopperPickaxeItem;
import net.mcreator.creativeworld.item.CopperHoeItem;
import net.mcreator.creativeworld.item.CopperAxeItem;
import net.mcreator.creativeworld.item.CopperArmorItem;
import net.mcreator.creativeworld.item.CompositeplateItem;
import net.mcreator.creativeworld.item.Composite_plate_toolSwordItem;
import net.mcreator.creativeworld.item.Composite_plate_toolShovelItem;
import net.mcreator.creativeworld.item.Composite_plate_toolPickaxeItem;
import net.mcreator.creativeworld.item.Composite_plate_toolHoeItem;
import net.mcreator.creativeworld.item.Composite_plate_toolAxeItem;
import net.mcreator.creativeworld.item.Composite_plate_armorArmorItem;
import net.mcreator.creativeworld.item.CoaldustItem;
import net.mcreator.creativeworld.item.CarbonplateItem;
import net.mcreator.creativeworld.item.BronzeplateItem;
import net.mcreator.creativeworld.item.BronzedustItem;
import net.mcreator.creativeworld.item.BronzeSwordItem;
import net.mcreator.creativeworld.item.BronzeShovelItem;
import net.mcreator.creativeworld.item.BronzePickaxeItem;
import net.mcreator.creativeworld.item.BronzeIngotItem;
import net.mcreator.creativeworld.item.BronzeHoeItem;
import net.mcreator.creativeworld.item.BronzeAxeItem;
import net.mcreator.creativeworld.item.BronzeArmorItem;
import net.mcreator.creativeworld.item.BedrockbreackerItem;
import net.mcreator.creativeworld.item.Battrey3Item;
import net.mcreator.creativeworld.item.Battrey2Item;
import net.mcreator.creativeworld.item.Battrey1Item;
import net.mcreator.creativeworld.item.Battrey0Item;
import net.mcreator.creativeworld.item.Alargebucketofwater9Item;
import net.mcreator.creativeworld.item.AlargebucketItem;
import net.mcreator.creativeworld.item.AdvancedelectricjetpackItem;
import net.mcreator.creativeworld.item.AdvanceddrillItem;
import net.mcreator.creativeworld.item.AccumulatiumnuggetItem;
import net.mcreator.creativeworld.item.AccumulatiumSwordItem;
import net.mcreator.creativeworld.item.AccumulatiumShovelItem;
import net.mcreator.creativeworld.item.AccumulatiumPickaxeItem;
import net.mcreator.creativeworld.item.AccumulatiumIngotItem;
import net.mcreator.creativeworld.item.AccumulatiumHoeItem;
import net.mcreator.creativeworld.item.AccumulatiumAxeItem;
import net.mcreator.creativeworld.item.AccumulatiumArmorItem;
import net.mcreator.creativeworld.item.ALargeBucketOfFluid9Item;
import net.mcreator.creativeworld.CreativeWorldMod;

import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;

public class CreativeWorldModItems {
	public static Item ENDLESSWATERSOURCE;
	public static Item ALARGEBUCKET;
	public static Item ALARGEBUCKETOFWATER_9;
	public static Item A_LARGE_BUCKET_OF_FLUID_9;
	public static Item RUBBER;
	public static Item LATEX;
	public static Item COALDUST;
	public static Item BRONZEDUST;
	public static Item CRUSHEDTINORE;
	public static Item WASHEDCRUSHEDTINORE;
	public static Item CRUSHEDCOPPERORE;
	public static Item WASHEDCRUSHEDCOPPERORE;
	public static Item CRUSHEDIRONORE;
	public static Item WASHEDCRUSHEDIRONORE;
	public static Item RAWTITAN;
	public static Item RAWTIN;
	public static Item TIN_INGOT;
	public static Item BRONZE_INGOT;
	public static Item TITAN_INGOT;
	public static Item ACCUMULATIUM_INGOT;
	public static Item CREATIVIUM_INGOT;
	public static Item TINNUGGET;
	public static Item COPPERNUGGET;
	public static Item ACCUMULATIUMNUGGET;
	public static Item CREATIVIUMNUGGET;
	public static Item TINPLATE;
	public static Item COPPERPLATE;
	public static Item IRONPLATE;
	public static Item COMPOSITEPLATE;
	public static Item CARBONPLATE;
	public static Item BRONZEPLATE;
	public static Item TITANPLATE;
	public static Item TINCOVER;
	public static Item THECOREOFMATTER;
	public static Item THECOREOFTHEFORMATION;
	public static Item CREATINGCORE;
	public static Item ELECTRICALCIRCUIT;
	public static Item THECOREOFINVULNERABILITY;
	public static Item CREATIVEMOD;
	public static Item REEL;
	public static Item CREATIVEREEL;
	public static Item COPPER_WIRE;
	public static Item INSULATED_COPPER_WIRE;
	public static Item BATTREY_0;
	public static Item BATTREY_1;
	public static Item BATTREY_2;
	public static Item BATTREY_3;
	public static Item TIN_PICKAXE;
	public static Item TIN_AXE;
	public static Item TIN_SHOVEL;
	public static Item TIN_HOE;
	public static Item COPPER_PICKAXE;
	public static Item COPPER_AXE;
	public static Item COPPER_SHOVEL;
	public static Item COPPER_HOE;
	public static Item BRONZE_PICKAXE;
	public static Item BRONZE_AXE;
	public static Item BRONZE_SHOVEL;
	public static Item BRONZE_HOE;
	public static Item CREATIVIUM_PICKAXE;
	public static Item CREATIVIUM_AXE;
	public static Item CREATIVIUM_SHOVEL;
	public static Item CREATIVIUM_HOE;
	public static Item ACCUMULATIUM_PICKAXE;
	public static Item ACCUMULATIUM_AXE;
	public static Item ACCUMULATIUM_SHOVEL;
	public static Item ACCUMULATIUM_HOE;
	public static Item TITAN_PICKAXE;
	public static Item TITAN_AXE;
	public static Item TITAN_SHOVEL;
	public static Item TITAN_HOE;
	public static Item COMPOSITE_PLATE_TOOL_PICKAXE;
	public static Item COMPOSITE_PLATE_TOOL_AXE;
	public static Item COMPOSITE_PLATE_TOOL_SHOVEL;
	public static Item COMPOSITE_PLATE_TOOL_HOE;
	public static Item BEDROCKBREACKER;
	public static Item DRILL;
	public static Item ADVANCEDDRILL;
	public static Item CREATIVEDRILL;
	public static Item IRONHAMMER;
	public static Item IRONWRENCH;
	public static Item WIRECUTTERS;
	public static Item TAP;
	public static Item IRON_MORTAR;
	public static Item ENERGYDETECTOR;
	public static Item PARTICLEBINDER;
	public static Item KEYCARD;
	public static Item TIN_ORE;
	public static Item TITAN_ORE;
	public static Item ACCUMULATIUM_ORE;
	public static Item CREATIVIUM_ORE;
	public static Item TIN_BLOCK;
	public static Item BRONZE_BLOCK;
	public static Item ACCUMULATIUM_BLOCK;
	public static Item CREATIVIUM_BLOCK;
	public static Item RESIN_LOG;
	public static Item RSINLOGWITHRESIN;
	public static Item RESIN_WOOD;
	public static Item RESIN_PLANKS;
	public static Item RESIN_STAIRS;
	public static Item RESIN_SLAB;
	public static Item RESIN_LEAVES;
	public static Item RESIN_FENCE;
	public static Item RESIN_FENCE_GATE;
	public static Item TITAN_BLOCK;
	public static Item MACHINECASE;
	public static Item COALGENERATOR;
	public static Item CRUSHER;
	public static Item FAN;
	public static Item BATTERYBLOCK;
	public static Item SOLARPANEL;
	public static Item ADVENCEDMACHINECASE;
	public static Item ADVENCEDSOLARPANEL;
	public static Item INFINITYENERGY;
	public static Item QUANTUMTELEPORTERBLOCK;
	public static Item QUANTUMTELEPORTERBLOCK_2;
	public static Item STATIONARYPARTICLEBINDER;
	public static Item RESINTREESAPLING;
	public static Item TIN_SWORD;
	public static Item TIN_ARMOR_HELMET;
	public static Item TIN_ARMOR_CHESTPLATE;
	public static Item TIN_ARMOR_LEGGINGS;
	public static Item TIN_ARMOR_BOOTS;
	public static Item COPPER_SWORD;
	public static Item COPPER_ARMOR_HELMET;
	public static Item COPPER_ARMOR_CHESTPLATE;
	public static Item COPPER_ARMOR_LEGGINGS;
	public static Item COPPER_ARMOR_BOOTS;
	public static Item BRONZE_SWORD;
	public static Item BRONZE_ARMOR_HELMET;
	public static Item BRONZE_ARMOR_CHESTPLATE;
	public static Item BRONZE_ARMOR_LEGGINGS;
	public static Item BRONZE_ARMOR_BOOTS;
	public static Item COMPOSITE_PLATE_TOOL_SWORD;
	public static Item COMPOSITE_PLATE_ARMOR_ARMOR_HELMET;
	public static Item COMPOSITE_PLATE_ARMOR_ARMOR_CHESTPLATE;
	public static Item COMPOSITE_PLATE_ARMOR_ARMOR_LEGGINGS;
	public static Item COMPOSITE_PLATE_ARMOR_ARMOR_BOOTS;
	public static Item TITAN_SWORD;
	public static Item TITAN_ARMOR_HELMET;
	public static Item TITAN_ARMOR_CHESTPLATE;
	public static Item TITAN_ARMOR_LEGGINGS;
	public static Item TITAN_ARMOR_BOOTS;
	public static Item ACCUMULATIUM_SWORD;
	public static Item ACCUMULATIUM_ARMOR_HELMET;
	public static Item ACCUMULATIUM_ARMOR_CHESTPLATE;
	public static Item ACCUMULATIUM_ARMOR_LEGGINGS;
	public static Item ACCUMULATIUM_ARMOR_BOOTS;
	public static Item CREATIVIUM_SWORD;
	public static Item CREATIVIUM_ARMOR_HELMET;
	public static Item CREATIVIUM_ARMOR_CHESTPLATE;
	public static Item CREATIVIUM_ARMOR_LEGGINGS;
	public static Item CREATIVIUM_ARMOR_BOOTS;
	public static Item ELECTRICJETPACK_CHESTPLATE;
	public static Item ADVANCEDELECTRICJETPACK_CHESTPLATE;
	public static Item COALGENERATOR_1;
	public static Item BUG;
	public static Item ELECTRIC_MOTOR;
	public static Item CREATIVE_ELECTRIC_MOTOR;

	public static void load() {
		ENDLESSWATERSOURCE = register("endlesswatersource", new EndlesswatersourceItem());
		ALARGEBUCKET = register("alargebucket", new AlargebucketItem());
		ALARGEBUCKETOFWATER_9 = register("alargebucketofwater_9", new Alargebucketofwater9Item());
		A_LARGE_BUCKET_OF_FLUID_9 = register("a_large_bucket_of_fluid_9", new ALargeBucketOfFluid9Item());
		RUBBER = register("rubber", new RubberItem());
		LATEX = register("latex", new LatexItem());
		COALDUST = register("coaldust", new CoaldustItem());
		BRONZEDUST = register("bronzedust", new BronzedustItem());
		CRUSHEDTINORE = register("crushedtinore", new CrushedtinoreItem());
		WASHEDCRUSHEDTINORE = register("washedcrushedtinore", new WashedcrushedtinoreItem());
		CRUSHEDCOPPERORE = register("crushedcopperore", new CrushedcopperoreItem());
		WASHEDCRUSHEDCOPPERORE = register("washedcrushedcopperore", new WashedcrushedcopperoreItem());
		CRUSHEDIRONORE = register("crushedironore", new CrushedironoreItem());
		WASHEDCRUSHEDIRONORE = register("washedcrushedironore", new WashedcrushedironoreItem());
		RAWTITAN = register("rawtitan", new RawtitanItem());
		RAWTIN = register("rawtin", new RawtinItem());
		TIN_INGOT = register("tin_ingot", new TinIngotItem());
		BRONZE_INGOT = register("bronze_ingot", new BronzeIngotItem());
		TITAN_INGOT = register("titan_ingot", new TitanIngotItem());
		ACCUMULATIUM_INGOT = register("accumulatium_ingot", new AccumulatiumIngotItem());
		CREATIVIUM_INGOT = register("creativium_ingot", new CreativiumIngotItem());
		TINNUGGET = register("tinnugget", new TinnuggetItem());
		COPPERNUGGET = register("coppernugget", new CoppernuggetItem());
		ACCUMULATIUMNUGGET = register("accumulatiumnugget", new AccumulatiumnuggetItem());
		CREATIVIUMNUGGET = register("creativiumnugget", new CreativiumnuggetItem());
		TINPLATE = register("tinplate", new TinplateItem());
		COPPERPLATE = register("copperplate", new CopperplateItem());
		IRONPLATE = register("ironplate", new IronplateItem());
		COMPOSITEPLATE = register("compositeplate", new CompositeplateItem());
		CARBONPLATE = register("carbonplate", new CarbonplateItem());
		BRONZEPLATE = register("bronzeplate", new BronzeplateItem());
		TITANPLATE = register("titanplate", new TitanplateItem());
		TINCOVER = register("tincover", new TincoverItem());
		THECOREOFMATTER = register("thecoreofmatter", new ThecoreofmatterItem());
		THECOREOFTHEFORMATION = register("thecoreoftheformation", new ThecoreoftheformationItem());
		CREATINGCORE = register("creatingcore", new CreatingcoreItem());
		ELECTRICALCIRCUIT = register("electricalcircuit", new ElectricalcircuitItem());
		THECOREOFINVULNERABILITY = register("thecoreofinvulnerability", new ThecoreofinvulnerabilityItem());
		CREATIVEMOD = register("creativemod", new CreativemodItem());
		REEL = register("reel", new ReelItem());
		CREATIVEREEL = register("creativereel", new CreativereelItem());
		COPPER_WIRE = register("copper_wire", new BlockItem(CreativeWorldModBlocks.COPPER_WIRE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDITEMS).register(content -> content.accept(COPPER_WIRE));
		INSULATED_COPPER_WIRE = register("insulated_copper_wire", new BlockItem(CreativeWorldModBlocks.INSULATED_COPPER_WIRE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDITEMS).register(content -> content.accept(INSULATED_COPPER_WIRE));
		BATTREY_0 = register("battrey_0", new Battrey0Item());
		BATTREY_1 = register("battrey_1", new Battrey1Item());
		BATTREY_2 = register("battrey_2", new Battrey2Item());
		BATTREY_3 = register("battrey_3", new Battrey3Item());
		TIN_PICKAXE = register("tin_pickaxe", new TinPickaxeItem());
		TIN_AXE = register("tin_axe", new TinAxeItem());
		TIN_SHOVEL = register("tin_shovel", new TinShovelItem());
		TIN_HOE = register("tin_hoe", new TinHoeItem());
		COPPER_PICKAXE = register("copper_pickaxe", new CopperPickaxeItem());
		COPPER_AXE = register("copper_axe", new CopperAxeItem());
		COPPER_SHOVEL = register("copper_shovel", new CopperShovelItem());
		COPPER_HOE = register("copper_hoe", new CopperHoeItem());
		BRONZE_PICKAXE = register("bronze_pickaxe", new BronzePickaxeItem());
		BRONZE_AXE = register("bronze_axe", new BronzeAxeItem());
		BRONZE_SHOVEL = register("bronze_shovel", new BronzeShovelItem());
		BRONZE_HOE = register("bronze_hoe", new BronzeHoeItem());
		CREATIVIUM_PICKAXE = register("creativium_pickaxe", new CreativiumPickaxeItem());
		CREATIVIUM_AXE = register("creativium_axe", new CreativiumAxeItem());
		CREATIVIUM_SHOVEL = register("creativium_shovel", new CreativiumShovelItem());
		CREATIVIUM_HOE = register("creativium_hoe", new CreativiumHoeItem());
		ACCUMULATIUM_PICKAXE = register("accumulatium_pickaxe", new AccumulatiumPickaxeItem());
		ACCUMULATIUM_AXE = register("accumulatium_axe", new AccumulatiumAxeItem());
		ACCUMULATIUM_SHOVEL = register("accumulatium_shovel", new AccumulatiumShovelItem());
		ACCUMULATIUM_HOE = register("accumulatium_hoe", new AccumulatiumHoeItem());
		TITAN_PICKAXE = register("titan_pickaxe", new TitanPickaxeItem());
		TITAN_AXE = register("titan_axe", new TitanAxeItem());
		TITAN_SHOVEL = register("titan_shovel", new TitanShovelItem());
		TITAN_HOE = register("titan_hoe", new TitanHoeItem());
		COMPOSITE_PLATE_TOOL_PICKAXE = register("composite_plate_tool_pickaxe", new Composite_plate_toolPickaxeItem());
		COMPOSITE_PLATE_TOOL_AXE = register("composite_plate_tool_axe", new Composite_plate_toolAxeItem());
		COMPOSITE_PLATE_TOOL_SHOVEL = register("composite_plate_tool_shovel", new Composite_plate_toolShovelItem());
		COMPOSITE_PLATE_TOOL_HOE = register("composite_plate_tool_hoe", new Composite_plate_toolHoeItem());
		BEDROCKBREACKER = register("bedrockbreacker", new BedrockbreackerItem());
		DRILL = register("drill", new DrillItem());
		ADVANCEDDRILL = register("advanceddrill", new AdvanceddrillItem());
		CREATIVEDRILL = register("creativedrill", new CreativedrillItem());
		IRONHAMMER = register("ironhammer", new IronhammerItem());
		IRONWRENCH = register("ironwrench", new IronwrenchItem());
		WIRECUTTERS = register("wirecutters", new WirecuttersItem());
		TAP = register("tap", new TapItem());
		IRON_MORTAR = register("iron_mortar", new IronMortarItem());
		ENERGYDETECTOR = register("energydetector", new EnergydetectorItem());
		PARTICLEBINDER = register("particlebinder", new ParticlebinderItem());
		KEYCARD = register("keycard", new KeycardItem());
		TIN_ORE = register("tin_ore", new BlockItem(CreativeWorldModBlocks.TIN_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(TIN_ORE));
		TITAN_ORE = register("titan_ore", new BlockItem(CreativeWorldModBlocks.TITAN_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(TITAN_ORE));
		ACCUMULATIUM_ORE = register("accumulatium_ore", new BlockItem(CreativeWorldModBlocks.ACCUMULATIUM_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(ACCUMULATIUM_ORE));
		CREATIVIUM_ORE = register("creativium_ore", new BlockItem(CreativeWorldModBlocks.CREATIVIUM_ORE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(CREATIVIUM_ORE));
		TIN_BLOCK = register("tin_block", new BlockItem(CreativeWorldModBlocks.TIN_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(TIN_BLOCK));
		BRONZE_BLOCK = register("bronze_block", new BlockItem(CreativeWorldModBlocks.BRONZE_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(BRONZE_BLOCK));
		ACCUMULATIUM_BLOCK = register("accumulatium_block", new BlockItem(CreativeWorldModBlocks.ACCUMULATIUM_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(ACCUMULATIUM_BLOCK));
		CREATIVIUM_BLOCK = register("creativium_block", new BlockItem(CreativeWorldModBlocks.CREATIVIUM_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(CREATIVIUM_BLOCK));
		RESIN_LOG = register("resin_log", new BlockItem(CreativeWorldModBlocks.RESIN_LOG, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESIN_LOG));
		RSINLOGWITHRESIN = register("rsinlogwithresin", new BlockItem(CreativeWorldModBlocks.RSINLOGWITHRESIN, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RSINLOGWITHRESIN));
		RESIN_WOOD = register("resin_wood", new BlockItem(CreativeWorldModBlocks.RESIN_WOOD, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESIN_WOOD));
		RESIN_PLANKS = register("resin_planks", new BlockItem(CreativeWorldModBlocks.RESIN_PLANKS, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESIN_PLANKS));
		RESIN_STAIRS = register("resin_stairs", new BlockItem(CreativeWorldModBlocks.RESIN_STAIRS, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESIN_STAIRS));
		RESIN_SLAB = register("resin_slab", new BlockItem(CreativeWorldModBlocks.RESIN_SLAB, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESIN_SLAB));
		RESIN_LEAVES = register("resin_leaves", new BlockItem(CreativeWorldModBlocks.RESIN_LEAVES, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESIN_LEAVES));
		RESIN_FENCE = register("resin_fence", new BlockItem(CreativeWorldModBlocks.RESIN_FENCE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESIN_FENCE));
		RESIN_FENCE_GATE = register("resin_fence_gate", new BlockItem(CreativeWorldModBlocks.RESIN_FENCE_GATE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESIN_FENCE_GATE));
		TITAN_BLOCK = register("titan_block", new BlockItem(CreativeWorldModBlocks.TITAN_BLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(TITAN_BLOCK));
		MACHINECASE = register("machinecase", new BlockItem(CreativeWorldModBlocks.MACHINECASE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(MACHINECASE));
		COALGENERATOR = register("coalgenerator", new BlockItem(CreativeWorldModBlocks.COALGENERATOR, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(COALGENERATOR));
		CRUSHER = register("crusher", new BlockItem(CreativeWorldModBlocks.CRUSHER, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(CRUSHER));
		FAN = register("fan", new BlockItem(CreativeWorldModBlocks.FAN, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(FAN));
		BATTERYBLOCK = register("batteryblock", new BlockItem(CreativeWorldModBlocks.BATTERYBLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(BATTERYBLOCK));
		SOLARPANEL = register("solarpanel", new BlockItem(CreativeWorldModBlocks.SOLARPANEL, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(SOLARPANEL));
		ADVENCEDMACHINECASE = register("advencedmachinecase", new BlockItem(CreativeWorldModBlocks.ADVENCEDMACHINECASE, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(ADVENCEDMACHINECASE));
		ADVENCEDSOLARPANEL = register("advencedsolarpanel", new BlockItem(CreativeWorldModBlocks.ADVENCEDSOLARPANEL, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(ADVENCEDSOLARPANEL));
		INFINITYENERGY = register("infinityenergy", new BlockItem(CreativeWorldModBlocks.INFINITYENERGY, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(INFINITYENERGY));
		QUANTUMTELEPORTERBLOCK = register("quantumteleporterblock", new BlockItem(CreativeWorldModBlocks.QUANTUMTELEPORTERBLOCK, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(QUANTUMTELEPORTERBLOCK));
		QUANTUMTELEPORTERBLOCK_2 = register("quantumteleporterblock_2", new BlockItem(CreativeWorldModBlocks.QUANTUMTELEPORTERBLOCK_2, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(QUANTUMTELEPORTERBLOCK_2));
		STATIONARYPARTICLEBINDER = register("stationaryparticlebinder", new BlockItem(CreativeWorldModBlocks.STATIONARYPARTICLEBINDER, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(STATIONARYPARTICLEBINDER));
		RESINTREESAPLING = register("resintreesapling", new BlockItem(CreativeWorldModBlocks.RESINTREESAPLING, new Item.Properties()));
		ItemGroupEvents.modifyEntriesEvent(CreativeWorldModTabs.TAB_CREATIVEWORLDBLOCKS).register(content -> content.accept(RESINTREESAPLING));
		TIN_SWORD = register("tin_sword", new TinSwordItem());
		TIN_ARMOR_HELMET = register("tin_armor_helmet", new TinArmorItem.Helmet());
		TIN_ARMOR_CHESTPLATE = register("tin_armor_chestplate", new TinArmorItem.Chestplate());
		TIN_ARMOR_LEGGINGS = register("tin_armor_leggings", new TinArmorItem.Leggings());
		TIN_ARMOR_BOOTS = register("tin_armor_boots", new TinArmorItem.Boots());
		COPPER_SWORD = register("copper_sword", new CopperSwordItem());
		COPPER_ARMOR_HELMET = register("copper_armor_helmet", new CopperArmorItem.Helmet());
		COPPER_ARMOR_CHESTPLATE = register("copper_armor_chestplate", new CopperArmorItem.Chestplate());
		COPPER_ARMOR_LEGGINGS = register("copper_armor_leggings", new CopperArmorItem.Leggings());
		COPPER_ARMOR_BOOTS = register("copper_armor_boots", new CopperArmorItem.Boots());
		BRONZE_SWORD = register("bronze_sword", new BronzeSwordItem());
		BRONZE_ARMOR_HELMET = register("bronze_armor_helmet", new BronzeArmorItem.Helmet());
		BRONZE_ARMOR_CHESTPLATE = register("bronze_armor_chestplate", new BronzeArmorItem.Chestplate());
		BRONZE_ARMOR_LEGGINGS = register("bronze_armor_leggings", new BronzeArmorItem.Leggings());
		BRONZE_ARMOR_BOOTS = register("bronze_armor_boots", new BronzeArmorItem.Boots());
		COMPOSITE_PLATE_TOOL_SWORD = register("composite_plate_tool_sword", new Composite_plate_toolSwordItem());
		COMPOSITE_PLATE_ARMOR_ARMOR_HELMET = register("composite_plate_armor_armor_helmet", new Composite_plate_armorArmorItem.Helmet());
		COMPOSITE_PLATE_ARMOR_ARMOR_CHESTPLATE = register("composite_plate_armor_armor_chestplate", new Composite_plate_armorArmorItem.Chestplate());
		COMPOSITE_PLATE_ARMOR_ARMOR_LEGGINGS = register("composite_plate_armor_armor_leggings", new Composite_plate_armorArmorItem.Leggings());
		COMPOSITE_PLATE_ARMOR_ARMOR_BOOTS = register("composite_plate_armor_armor_boots", new Composite_plate_armorArmorItem.Boots());
		TITAN_SWORD = register("titan_sword", new TitanSwordItem());
		TITAN_ARMOR_HELMET = register("titan_armor_helmet", new TitanArmorItem.Helmet());
		TITAN_ARMOR_CHESTPLATE = register("titan_armor_chestplate", new TitanArmorItem.Chestplate());
		TITAN_ARMOR_LEGGINGS = register("titan_armor_leggings", new TitanArmorItem.Leggings());
		TITAN_ARMOR_BOOTS = register("titan_armor_boots", new TitanArmorItem.Boots());
		ACCUMULATIUM_SWORD = register("accumulatium_sword", new AccumulatiumSwordItem());
		ACCUMULATIUM_ARMOR_HELMET = register("accumulatium_armor_helmet", new AccumulatiumArmorItem.Helmet());
		ACCUMULATIUM_ARMOR_CHESTPLATE = register("accumulatium_armor_chestplate", new AccumulatiumArmorItem.Chestplate());
		ACCUMULATIUM_ARMOR_LEGGINGS = register("accumulatium_armor_leggings", new AccumulatiumArmorItem.Leggings());
		ACCUMULATIUM_ARMOR_BOOTS = register("accumulatium_armor_boots", new AccumulatiumArmorItem.Boots());
		CREATIVIUM_SWORD = register("creativium_sword", new CreativiumSwordItem());
		CREATIVIUM_ARMOR_HELMET = register("creativium_armor_helmet", new CreativiumArmorItem.Helmet());
		CREATIVIUM_ARMOR_CHESTPLATE = register("creativium_armor_chestplate", new CreativiumArmorItem.Chestplate());
		CREATIVIUM_ARMOR_LEGGINGS = register("creativium_armor_leggings", new CreativiumArmorItem.Leggings());
		CREATIVIUM_ARMOR_BOOTS = register("creativium_armor_boots", new CreativiumArmorItem.Boots());
		ELECTRICJETPACK_CHESTPLATE = register("electricjetpack_chestplate", new ElectricjetpackItem.Chestplate());
		ADVANCEDELECTRICJETPACK_CHESTPLATE = register("advancedelectricjetpack_chestplate", new AdvancedelectricjetpackItem.Chestplate());
		COALGENERATOR_1 = register("coalgenerator_1", new BlockItem(CreativeWorldModBlocks.COALGENERATOR_1, new Item.Properties()));
		BUG = register("bug", new BlockItem(CreativeWorldModBlocks.BUG, new Item.Properties()));
		ELECTRIC_MOTOR = register("electric_motor", new ElectricMotorItem());
		CREATIVE_ELECTRIC_MOTOR = register("creative_electric_motor", new CreativeElectricMotorItem());
	}

	public static void clientLoad() {
	}

	private static Item register(String registryName, Item item) {
		return Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(CreativeWorldMod.MODID, registryName), item);
	}

	private static void registerBlockingProperty(Item item) {
		ItemProperties.register(item, new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
	}
}
