
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.creativeworld.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.bus.api.IEventBus;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.core.registries.BuiltInRegistries;

import net.mcreator.creativeworld.item.WirecuttersItem;
import net.mcreator.creativeworld.item.WashedcrushedtinoreItem;
import net.mcreator.creativeworld.item.WashedcrushedironoreItem;
import net.mcreator.creativeworld.item.WashedcrushedcopperoreItem;
import net.mcreator.creativeworld.item.TitanplateItem;
import net.mcreator.creativeworld.item.TitanSwordItem;
import net.mcreator.creativeworld.item.TitanShovelItem;
import net.mcreator.creativeworld.item.TitanPickaxeItem;
import net.mcreator.creativeworld.item.TitanIngotItem;
import net.mcreator.creativeworld.item.TitanHoeItem;
import net.mcreator.creativeworld.item.TitanAxeItem;
import net.mcreator.creativeworld.item.TitanArmorItem;
import net.mcreator.creativeworld.item.TinplateItem;
import net.mcreator.creativeworld.item.TinnuggetItem;
import net.mcreator.creativeworld.item.TincoverItem;
import net.mcreator.creativeworld.item.TinSwordItem;
import net.mcreator.creativeworld.item.TinShovelItem;
import net.mcreator.creativeworld.item.TinPickaxeItem;
import net.mcreator.creativeworld.item.TinIngotItem;
import net.mcreator.creativeworld.item.TinHoeItem;
import net.mcreator.creativeworld.item.TinAxeItem;
import net.mcreator.creativeworld.item.TinArmorItem;
import net.mcreator.creativeworld.item.ThecoreoftheformationItem;
import net.mcreator.creativeworld.item.ThecoreofmatterItem;
import net.mcreator.creativeworld.item.ThecoreofinvulnerabilityItem;
import net.mcreator.creativeworld.item.TapItem;
import net.mcreator.creativeworld.item.RubberItem;
import net.mcreator.creativeworld.item.ReelItem;
import net.mcreator.creativeworld.item.RawtitanItem;
import net.mcreator.creativeworld.item.RawtinItem;
import net.mcreator.creativeworld.item.ParticlebinderItem;
import net.mcreator.creativeworld.item.OilItem;
import net.mcreator.creativeworld.item.LatexItem;
import net.mcreator.creativeworld.item.KeycardItem;
import net.mcreator.creativeworld.item.IronwrenchItem;
import net.mcreator.creativeworld.item.IronplateItem;
import net.mcreator.creativeworld.item.IronhammerItem;
import net.mcreator.creativeworld.item.IronMortarItem;
import net.mcreator.creativeworld.item.GasItem;
import net.mcreator.creativeworld.item.EnergydetectorItem;
import net.mcreator.creativeworld.item.EndlesswatersourceItem;
import net.mcreator.creativeworld.item.ElectricjetpackItem;
import net.mcreator.creativeworld.item.ElectricalcircuitItem;
import net.mcreator.creativeworld.item.ElectricMotorItem;
import net.mcreator.creativeworld.item.DrillItem;
import net.mcreator.creativeworld.item.CrushedtinoreItem;
import net.mcreator.creativeworld.item.CrushedironoreItem;
import net.mcreator.creativeworld.item.CrushedcopperoreItem;
import net.mcreator.creativeworld.item.CreativiumnuggetItem;
import net.mcreator.creativeworld.item.CreativiumSwordItem;
import net.mcreator.creativeworld.item.CreativiumShovelItem;
import net.mcreator.creativeworld.item.CreativiumPickaxeItem;
import net.mcreator.creativeworld.item.CreativiumIngotItem;
import net.mcreator.creativeworld.item.CreativiumHoeItem;
import net.mcreator.creativeworld.item.CreativiumAxeItem;
import net.mcreator.creativeworld.item.CreativiumArmorItem;
import net.mcreator.creativeworld.item.CreativereelItem;
import net.mcreator.creativeworld.item.CreativemodItem;
import net.mcreator.creativeworld.item.CreativedrillItem;
import net.mcreator.creativeworld.item.CreativeElectricMotorItem;
import net.mcreator.creativeworld.item.CreatingcoreItem;
import net.mcreator.creativeworld.item.CopperplateItem;
import net.mcreator.creativeworld.item.CoppernuggetItem;
import net.mcreator.creativeworld.item.CopperSwordItem;
import net.mcreator.creativeworld.item.CopperShovelItem;
import net.mcreator.creativeworld.item.CopperPickaxeItem;
import net.mcreator.creativeworld.item.CopperHoeItem;
import net.mcreator.creativeworld.item.CopperAxeItem;
import net.mcreator.creativeworld.item.CopperArmorItem;
import net.mcreator.creativeworld.item.CompositeplateItem;
import net.mcreator.creativeworld.item.Composite_plate_toolSwordItem;
import net.mcreator.creativeworld.item.Composite_plate_toolShovelItem;
import net.mcreator.creativeworld.item.Composite_plate_toolPickaxeItem;
import net.mcreator.creativeworld.item.Composite_plate_toolHoeItem;
import net.mcreator.creativeworld.item.Composite_plate_toolAxeItem;
import net.mcreator.creativeworld.item.Composite_plate_armorArmorItem;
import net.mcreator.creativeworld.item.CoaldustItem;
import net.mcreator.creativeworld.item.CarbonplateItem;
import net.mcreator.creativeworld.item.BronzeplateItem;
import net.mcreator.creativeworld.item.BronzedustItem;
import net.mcreator.creativeworld.item.BronzeSwordItem;
import net.mcreator.creativeworld.item.BronzeShovelItem;
import net.mcreator.creativeworld.item.BronzePickaxeItem;
import net.mcreator.creativeworld.item.BronzeIngotItem;
import net.mcreator.creativeworld.item.BronzeHoeItem;
import net.mcreator.creativeworld.item.BronzeAxeItem;
import net.mcreator.creativeworld.item.BronzeArmorItem;
import net.mcreator.creativeworld.item.BedrockbreackerItem;
import net.mcreator.creativeworld.item.Battrey3Item;
import net.mcreator.creativeworld.item.Battrey2Item;
import net.mcreator.creativeworld.item.Battrey1Item;
import net.mcreator.creativeworld.item.Battrey0Item;
import net.mcreator.creativeworld.item.Alargebucketofwater9Item;
import net.mcreator.creativeworld.item.AlargebucketItem;
import net.mcreator.creativeworld.item.AdvancedelectricjetpackItem;
import net.mcreator.creativeworld.item.AdvanceddrillItem;
import net.mcreator.creativeworld.item.AccumulatiumnuggetItem;
import net.mcreator.creativeworld.item.AccumulatiumSwordItem;
import net.mcreator.creativeworld.item.AccumulatiumShovelItem;
import net.mcreator.creativeworld.item.AccumulatiumPickaxeItem;
import net.mcreator.creativeworld.item.AccumulatiumIngotItem;
import net.mcreator.creativeworld.item.AccumulatiumHoeItem;
import net.mcreator.creativeworld.item.AccumulatiumAxeItem;
import net.mcreator.creativeworld.item.AccumulatiumArmorItem;
import net.mcreator.creativeworld.item.ALargeBucketOfFluid9Item;
import net.mcreator.creativeworld.CreativeWorldMod;

public class CreativeWorldModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(BuiltInRegistries.ITEM, CreativeWorldMod.MODID);
	public static final DeferredHolder<Item, Item> ENDLESSWATERSOURCE = REGISTRY.register("endlesswatersource", () -> new EndlesswatersourceItem());
	public static final DeferredHolder<Item, Item> ALARGEBUCKET = REGISTRY.register("alargebucket", () -> new AlargebucketItem());
	public static final DeferredHolder<Item, Item> ALARGEBUCKETOFWATER_9 = REGISTRY.register("alargebucketofwater_9", () -> new Alargebucketofwater9Item());
	public static final DeferredHolder<Item, Item> IRONWRENCH = REGISTRY.register("ironwrench", () -> new IronwrenchItem());
	public static final DeferredHolder<Item, Item> COALGENERATOR = block(CreativeWorldModBlocks.COALGENERATOR);
	public static final DeferredHolder<Item, Item> MACHINECASE = block(CreativeWorldModBlocks.MACHINECASE);
	public static final DeferredHolder<Item, Item> IRONHAMMER = REGISTRY.register("ironhammer", () -> new IronhammerItem());
	public static final DeferredHolder<Item, Item> IRONPLATE = REGISTRY.register("ironplate", () -> new IronplateItem());
	public static final DeferredHolder<Item, Item> TIN_INGOT = REGISTRY.register("tin_ingot", () -> new TinIngotItem());
	public static final DeferredHolder<Item, Item> TIN_ORE = block(CreativeWorldModBlocks.TIN_ORE);
	public static final DeferredHolder<Item, Item> TIN_BLOCK = block(CreativeWorldModBlocks.TIN_BLOCK);
	public static final DeferredHolder<Item, Item> TIN_PICKAXE = REGISTRY.register("tin_pickaxe", () -> new TinPickaxeItem());
	public static final DeferredHolder<Item, Item> TIN_AXE = REGISTRY.register("tin_axe", () -> new TinAxeItem());
	public static final DeferredHolder<Item, Item> TIN_SWORD = REGISTRY.register("tin_sword", () -> new TinSwordItem());
	public static final DeferredHolder<Item, Item> TIN_SHOVEL = REGISTRY.register("tin_shovel", () -> new TinShovelItem());
	public static final DeferredHolder<Item, Item> TIN_HOE = REGISTRY.register("tin_hoe", () -> new TinHoeItem());
	public static final DeferredHolder<Item, Item> TIN_ARMOR_HELMET = REGISTRY.register("tin_armor_helmet", () -> new TinArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> TIN_ARMOR_CHESTPLATE = REGISTRY.register("tin_armor_chestplate", () -> new TinArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> TIN_ARMOR_LEGGINGS = REGISTRY.register("tin_armor_leggings", () -> new TinArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> TIN_ARMOR_BOOTS = REGISTRY.register("tin_armor_boots", () -> new TinArmorItem.Boots());
	public static final DeferredHolder<Item, Item> COPPER_PICKAXE = REGISTRY.register("copper_pickaxe", () -> new CopperPickaxeItem());
	public static final DeferredHolder<Item, Item> COPPER_AXE = REGISTRY.register("copper_axe", () -> new CopperAxeItem());
	public static final DeferredHolder<Item, Item> COPPER_SWORD = REGISTRY.register("copper_sword", () -> new CopperSwordItem());
	public static final DeferredHolder<Item, Item> COPPER_SHOVEL = REGISTRY.register("copper_shovel", () -> new CopperShovelItem());
	public static final DeferredHolder<Item, Item> COPPER_HOE = REGISTRY.register("copper_hoe", () -> new CopperHoeItem());
	public static final DeferredHolder<Item, Item> COPPER_ARMOR_HELMET = REGISTRY.register("copper_armor_helmet", () -> new CopperArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> COPPER_ARMOR_CHESTPLATE = REGISTRY.register("copper_armor_chestplate", () -> new CopperArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> COPPER_ARMOR_LEGGINGS = REGISTRY.register("copper_armor_leggings", () -> new CopperArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> COPPER_ARMOR_BOOTS = REGISTRY.register("copper_armor_boots", () -> new CopperArmorItem.Boots());
	public static final DeferredHolder<Item, Item> TINPLATE = REGISTRY.register("tinplate", () -> new TinplateItem());
	public static final DeferredHolder<Item, Item> COPPERPLATE = REGISTRY.register("copperplate", () -> new CopperplateItem());
	public static final DeferredHolder<Item, Item> RESIN_WOOD = block(CreativeWorldModBlocks.RESIN_WOOD);
	public static final DeferredHolder<Item, Item> RESIN_LOG = block(CreativeWorldModBlocks.RESIN_LOG);
	public static final DeferredHolder<Item, Item> RESIN_PLANKS = block(CreativeWorldModBlocks.RESIN_PLANKS);
	public static final DeferredHolder<Item, Item> RESIN_LEAVES = block(CreativeWorldModBlocks.RESIN_LEAVES);
	public static final DeferredHolder<Item, Item> RESIN_STAIRS = block(CreativeWorldModBlocks.RESIN_STAIRS);
	public static final DeferredHolder<Item, Item> RESIN_SLAB = block(CreativeWorldModBlocks.RESIN_SLAB);
	public static final DeferredHolder<Item, Item> RESIN_FENCE = block(CreativeWorldModBlocks.RESIN_FENCE);
	public static final DeferredHolder<Item, Item> RESIN_FENCE_GATE = block(CreativeWorldModBlocks.RESIN_FENCE_GATE);
	public static final DeferredHolder<Item, Item> CRUSHER = block(CreativeWorldModBlocks.CRUSHER);
	public static final DeferredHolder<Item, Item> RSINLOGWITHRESIN = block(CreativeWorldModBlocks.RSINLOGWITHRESIN);
	public static final DeferredHolder<Item, Item> WIRECUTTERS = REGISTRY.register("wirecutters", () -> new WirecuttersItem());
	public static final DeferredHolder<Item, Item> THECOREOFTHEFORMATION = REGISTRY.register("thecoreoftheformation", () -> new ThecoreoftheformationItem());
	public static final DeferredHolder<Item, Item> THECOREOFMATTER = REGISTRY.register("thecoreofmatter", () -> new ThecoreofmatterItem());
	public static final DeferredHolder<Item, Item> CREATINGCORE = REGISTRY.register("creatingcore", () -> new CreatingcoreItem());
	public static final DeferredHolder<Item, Item> BEDROCKBREACKER = REGISTRY.register("bedrockbreacker", () -> new BedrockbreackerItem());
	public static final DeferredHolder<Item, Item> COALGENERATOR_1 = block(CreativeWorldModBlocks.COALGENERATOR_1);
	public static final DeferredHolder<Item, Item> SOLARPANEL = block(CreativeWorldModBlocks.SOLARPANEL);
	public static final DeferredHolder<Item, Item> CRUSHEDIRONORE = REGISTRY.register("crushedironore", () -> new CrushedironoreItem());
	public static final DeferredHolder<Item, Item> CRUSHEDCOPPERORE = REGISTRY.register("crushedcopperore", () -> new CrushedcopperoreItem());
	public static final DeferredHolder<Item, Item> CRUSHEDTINORE = REGISTRY.register("crushedtinore", () -> new CrushedtinoreItem());
	public static final DeferredHolder<Item, Item> TINNUGGET = REGISTRY.register("tinnugget", () -> new TinnuggetItem());
	public static final DeferredHolder<Item, Item> COPPERNUGGET = REGISTRY.register("coppernugget", () -> new CoppernuggetItem());
	public static final DeferredHolder<Item, Item> WASHEDCRUSHEDIRONORE = REGISTRY.register("washedcrushedironore", () -> new WashedcrushedironoreItem());
	public static final DeferredHolder<Item, Item> WASHEDCRUSHEDCOPPERORE = REGISTRY.register("washedcrushedcopperore", () -> new WashedcrushedcopperoreItem());
	public static final DeferredHolder<Item, Item> WASHEDCRUSHEDTINORE = REGISTRY.register("washedcrushedtinore", () -> new WashedcrushedtinoreItem());
	public static final DeferredHolder<Item, Item> CREATIVEMOD = REGISTRY.register("creativemod", () -> new CreativemodItem());
	public static final DeferredHolder<Item, Item> LATEX = REGISTRY.register("latex", () -> new LatexItem());
	public static final DeferredHolder<Item, Item> TAP = REGISTRY.register("tap", () -> new TapItem());
	public static final DeferredHolder<Item, Item> RUBBER = REGISTRY.register("rubber", () -> new RubberItem());
	public static final DeferredHolder<Item, Item> TINCOVER = REGISTRY.register("tincover", () -> new TincoverItem());
	public static final DeferredHolder<Item, Item> OIL_BUCKET = REGISTRY.register("oil_bucket", () -> new OilItem());
	public static final DeferredHolder<Item, Item> GAS_BUCKET = REGISTRY.register("gas_bucket", () -> new GasItem());
	public static final DeferredHolder<Item, Item> RAWTIN = REGISTRY.register("rawtin", () -> new RawtinItem());
	public static final DeferredHolder<Item, Item> BRONZEDUST = REGISTRY.register("bronzedust", () -> new BronzedustItem());
	public static final DeferredHolder<Item, Item> ENERGYDETECTOR = REGISTRY.register("energydetector", () -> new EnergydetectorItem());
	public static final DeferredHolder<Item, Item> FAN = block(CreativeWorldModBlocks.FAN);
	public static final DeferredHolder<Item, Item> BATTERYBLOCK = block(CreativeWorldModBlocks.BATTERYBLOCK);
	public static final DeferredHolder<Item, Item> ELECTRICJETPACK_CHESTPLATE = REGISTRY.register("electricjetpack_chestplate", () -> new ElectricjetpackItem.Chestplate());
	public static final DeferredHolder<Item, Item> BRONZE_INGOT = REGISTRY.register("bronze_ingot", () -> new BronzeIngotItem());
	public static final DeferredHolder<Item, Item> BRONZE_BLOCK = block(CreativeWorldModBlocks.BRONZE_BLOCK);
	public static final DeferredHolder<Item, Item> BRONZE_PICKAXE = REGISTRY.register("bronze_pickaxe", () -> new BronzePickaxeItem());
	public static final DeferredHolder<Item, Item> BRONZE_AXE = REGISTRY.register("bronze_axe", () -> new BronzeAxeItem());
	public static final DeferredHolder<Item, Item> BRONZE_SWORD = REGISTRY.register("bronze_sword", () -> new BronzeSwordItem());
	public static final DeferredHolder<Item, Item> BRONZE_SHOVEL = REGISTRY.register("bronze_shovel", () -> new BronzeShovelItem());
	public static final DeferredHolder<Item, Item> BRONZE_HOE = REGISTRY.register("bronze_hoe", () -> new BronzeHoeItem());
	public static final DeferredHolder<Item, Item> BRONZE_ARMOR_HELMET = REGISTRY.register("bronze_armor_helmet", () -> new BronzeArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> BRONZE_ARMOR_CHESTPLATE = REGISTRY.register("bronze_armor_chestplate", () -> new BronzeArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> BRONZE_ARMOR_LEGGINGS = REGISTRY.register("bronze_armor_leggings", () -> new BronzeArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> BRONZE_ARMOR_BOOTS = REGISTRY.register("bronze_armor_boots", () -> new BronzeArmorItem.Boots());
	public static final DeferredHolder<Item, Item> INFINITYENERGY = block(CreativeWorldModBlocks.INFINITYENERGY);
	public static final DeferredHolder<Item, Item> COALDUST = REGISTRY.register("coaldust", () -> new CoaldustItem());
	public static final DeferredHolder<Item, Item> ELECTRICALCIRCUIT = REGISTRY.register("electricalcircuit", () -> new ElectricalcircuitItem());
	public static final DeferredHolder<Item, Item> ADVANCEDELECTRICJETPACK_CHESTPLATE = REGISTRY.register("advancedelectricjetpack_chestplate", () -> new AdvancedelectricjetpackItem.Chestplate());
	public static final DeferredHolder<Item, Item> ADVENCEDMACHINECASE = block(CreativeWorldModBlocks.ADVENCEDMACHINECASE);
	public static final DeferredHolder<Item, Item> ADVENCEDSOLARPANEL = block(CreativeWorldModBlocks.ADVENCEDSOLARPANEL);
	public static final DeferredHolder<Item, Item> CREATIVIUM_INGOT = REGISTRY.register("creativium_ingot", () -> new CreativiumIngotItem());
	public static final DeferredHolder<Item, Item> CREATIVIUM_ORE = block(CreativeWorldModBlocks.CREATIVIUM_ORE);
	public static final DeferredHolder<Item, Item> CREATIVIUM_BLOCK = block(CreativeWorldModBlocks.CREATIVIUM_BLOCK);
	public static final DeferredHolder<Item, Item> CREATIVIUM_PICKAXE = REGISTRY.register("creativium_pickaxe", () -> new CreativiumPickaxeItem());
	public static final DeferredHolder<Item, Item> CREATIVIUM_AXE = REGISTRY.register("creativium_axe", () -> new CreativiumAxeItem());
	public static final DeferredHolder<Item, Item> CREATIVIUM_SWORD = REGISTRY.register("creativium_sword", () -> new CreativiumSwordItem());
	public static final DeferredHolder<Item, Item> CREATIVIUM_SHOVEL = REGISTRY.register("creativium_shovel", () -> new CreativiumShovelItem());
	public static final DeferredHolder<Item, Item> CREATIVIUM_HOE = REGISTRY.register("creativium_hoe", () -> new CreativiumHoeItem());
	public static final DeferredHolder<Item, Item> CREATIVIUM_ARMOR_HELMET = REGISTRY.register("creativium_armor_helmet", () -> new CreativiumArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> CREATIVIUM_ARMOR_CHESTPLATE = REGISTRY.register("creativium_armor_chestplate", () -> new CreativiumArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> CREATIVIUM_ARMOR_LEGGINGS = REGISTRY.register("creativium_armor_leggings", () -> new CreativiumArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> CREATIVIUM_ARMOR_BOOTS = REGISTRY.register("creativium_armor_boots", () -> new CreativiumArmorItem.Boots());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_INGOT = REGISTRY.register("accumulatium_ingot", () -> new AccumulatiumIngotItem());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_ORE = block(CreativeWorldModBlocks.ACCUMULATIUM_ORE);
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_BLOCK = block(CreativeWorldModBlocks.ACCUMULATIUM_BLOCK);
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_PICKAXE = REGISTRY.register("accumulatium_pickaxe", () -> new AccumulatiumPickaxeItem());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_AXE = REGISTRY.register("accumulatium_axe", () -> new AccumulatiumAxeItem());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_SWORD = REGISTRY.register("accumulatium_sword", () -> new AccumulatiumSwordItem());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_SHOVEL = REGISTRY.register("accumulatium_shovel", () -> new AccumulatiumShovelItem());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_HOE = REGISTRY.register("accumulatium_hoe", () -> new AccumulatiumHoeItem());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_ARMOR_HELMET = REGISTRY.register("accumulatium_armor_helmet", () -> new AccumulatiumArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_ARMOR_CHESTPLATE = REGISTRY.register("accumulatium_armor_chestplate", () -> new AccumulatiumArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_ARMOR_LEGGINGS = REGISTRY.register("accumulatium_armor_leggings", () -> new AccumulatiumArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> ACCUMULATIUM_ARMOR_BOOTS = REGISTRY.register("accumulatium_armor_boots", () -> new AccumulatiumArmorItem.Boots());
	public static final DeferredHolder<Item, Item> CREATIVIUMNUGGET = REGISTRY.register("creativiumnugget", () -> new CreativiumnuggetItem());
	public static final DeferredHolder<Item, Item> ACCUMULATIUMNUGGET = REGISTRY.register("accumulatiumnugget", () -> new AccumulatiumnuggetItem());
	public static final DeferredHolder<Item, Item> CARBONPLATE = REGISTRY.register("carbonplate", () -> new CarbonplateItem());
	public static final DeferredHolder<Item, Item> THECOREOFINVULNERABILITY = REGISTRY.register("thecoreofinvulnerability", () -> new ThecoreofinvulnerabilityItem());
	public static final DeferredHolder<Item, Item> BRONZEPLATE = REGISTRY.register("bronzeplate", () -> new BronzeplateItem());
	public static final DeferredHolder<Item, Item> TITAN_INGOT = REGISTRY.register("titan_ingot", () -> new TitanIngotItem());
	public static final DeferredHolder<Item, Item> TITAN_ORE = block(CreativeWorldModBlocks.TITAN_ORE);
	public static final DeferredHolder<Item, Item> TITAN_BLOCK = block(CreativeWorldModBlocks.TITAN_BLOCK);
	public static final DeferredHolder<Item, Item> TITAN_PICKAXE = REGISTRY.register("titan_pickaxe", () -> new TitanPickaxeItem());
	public static final DeferredHolder<Item, Item> TITAN_AXE = REGISTRY.register("titan_axe", () -> new TitanAxeItem());
	public static final DeferredHolder<Item, Item> TITAN_SWORD = REGISTRY.register("titan_sword", () -> new TitanSwordItem());
	public static final DeferredHolder<Item, Item> TITAN_SHOVEL = REGISTRY.register("titan_shovel", () -> new TitanShovelItem());
	public static final DeferredHolder<Item, Item> TITAN_HOE = REGISTRY.register("titan_hoe", () -> new TitanHoeItem());
	public static final DeferredHolder<Item, Item> TITAN_ARMOR_HELMET = REGISTRY.register("titan_armor_helmet", () -> new TitanArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> TITAN_ARMOR_CHESTPLATE = REGISTRY.register("titan_armor_chestplate", () -> new TitanArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> TITAN_ARMOR_LEGGINGS = REGISTRY.register("titan_armor_leggings", () -> new TitanArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> TITAN_ARMOR_BOOTS = REGISTRY.register("titan_armor_boots", () -> new TitanArmorItem.Boots());
	public static final DeferredHolder<Item, Item> TITANPLATE = REGISTRY.register("titanplate", () -> new TitanplateItem());
	public static final DeferredHolder<Item, Item> COMPOSITEPLATE = REGISTRY.register("compositeplate", () -> new CompositeplateItem());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_ARMOR_ARMOR_HELMET = REGISTRY.register("composite_plate_armor_armor_helmet", () -> new Composite_plate_armorArmorItem.Helmet());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("composite_plate_armor_armor_chestplate", () -> new Composite_plate_armorArmorItem.Chestplate());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("composite_plate_armor_armor_leggings", () -> new Composite_plate_armorArmorItem.Leggings());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_ARMOR_ARMOR_BOOTS = REGISTRY.register("composite_plate_armor_armor_boots", () -> new Composite_plate_armorArmorItem.Boots());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_TOOL_PICKAXE = REGISTRY.register("composite_plate_tool_pickaxe", () -> new Composite_plate_toolPickaxeItem());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_TOOL_AXE = REGISTRY.register("composite_plate_tool_axe", () -> new Composite_plate_toolAxeItem());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_TOOL_SWORD = REGISTRY.register("composite_plate_tool_sword", () -> new Composite_plate_toolSwordItem());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_TOOL_SHOVEL = REGISTRY.register("composite_plate_tool_shovel", () -> new Composite_plate_toolShovelItem());
	public static final DeferredHolder<Item, Item> COMPOSITE_PLATE_TOOL_HOE = REGISTRY.register("composite_plate_tool_hoe", () -> new Composite_plate_toolHoeItem());
	public static final DeferredHolder<Item, Item> PARTICLEBINDER = REGISTRY.register("particlebinder", () -> new ParticlebinderItem());
	public static final DeferredHolder<Item, Item> STATIONARYPARTICLEBINDER = block(CreativeWorldModBlocks.STATIONARYPARTICLEBINDER);
	public static final DeferredHolder<Item, Item> QUANTUMTELEPORTERBLOCK = block(CreativeWorldModBlocks.QUANTUMTELEPORTERBLOCK);
	public static final DeferredHolder<Item, Item> QUANTUMTELEPORTERBLOCK_2 = block(CreativeWorldModBlocks.QUANTUMTELEPORTERBLOCK_2);
	public static final DeferredHolder<Item, Item> KEYCARD = REGISTRY.register("keycard", () -> new KeycardItem());
	public static final DeferredHolder<Item, Item> DRILL = REGISTRY.register("drill", () -> new DrillItem());
	public static final DeferredHolder<Item, Item> ADVANCEDDRILL = REGISTRY.register("advanceddrill", () -> new AdvanceddrillItem());
	public static final DeferredHolder<Item, Item> CREATIVEDRILL = REGISTRY.register("creativedrill", () -> new CreativedrillItem());
	public static final DeferredHolder<Item, Item> REEL = REGISTRY.register("reel", () -> new ReelItem());
	public static final DeferredHolder<Item, Item> CREATIVEREEL = REGISTRY.register("creativereel", () -> new CreativereelItem());
	public static final DeferredHolder<Item, Item> RAWTITAN = REGISTRY.register("rawtitan", () -> new RawtitanItem());
	public static final DeferredHolder<Item, Item> RESINTREESAPLING = block(CreativeWorldModBlocks.RESINTREESAPLING);
	public static final DeferredHolder<Item, Item> IRON_MORTAR = REGISTRY.register("iron_mortar", () -> new IronMortarItem());
	public static final DeferredHolder<Item, Item> BUG = block(CreativeWorldModBlocks.BUG);
	public static final DeferredHolder<Item, Item> COPPER_WIRE = block(CreativeWorldModBlocks.COPPER_WIRE);
	public static final DeferredHolder<Item, Item> INSULATED_COPPER_WIRE = block(CreativeWorldModBlocks.INSULATED_COPPER_WIRE);
	public static final DeferredHolder<Item, Item> A_LARGE_BUCKET_OF_FLUID_9 = REGISTRY.register("a_large_bucket_of_fluid_9", () -> new ALargeBucketOfFluid9Item());
	public static final DeferredHolder<Item, Item> BATTREY_0 = REGISTRY.register("battrey_0", () -> new Battrey0Item());
	public static final DeferredHolder<Item, Item> BATTREY_1 = REGISTRY.register("battrey_1", () -> new Battrey1Item());
	public static final DeferredHolder<Item, Item> BATTREY_2 = REGISTRY.register("battrey_2", () -> new Battrey2Item());
	public static final DeferredHolder<Item, Item> BATTREY_3 = REGISTRY.register("battrey_3", () -> new Battrey3Item());
	public static final DeferredHolder<Item, Item> ELECTRIC_MOTOR = REGISTRY.register("electric_motor", () -> new ElectricMotorItem());
	public static final DeferredHolder<Item, Item> CREATIVE_ELECTRIC_MOTOR = REGISTRY.register("creative_electric_motor", () -> new CreativeElectricMotorItem());
	public static final DeferredHolder<Item, Item> NUCLEAR_REACTOR = block(CreativeWorldModBlocks.NUCLEAR_REACTOR);

	// Start of user code block custom items
	// End of user code block custom items
	public static void register(IEventBus bus) {
		REGISTRY.register(bus);
	}

	private static DeferredHolder<Item, Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
