
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.creativeworld.init;

import net.minecraft.world.level.block.Block;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.Registry;

import net.mcreator.creativeworld.block.TitanOreBlock;
import net.mcreator.creativeworld.block.TitanBlockBlock;
import net.mcreator.creativeworld.block.TinOreBlock;
import net.mcreator.creativeworld.block.TinBlockBlock;
import net.mcreator.creativeworld.block.StationaryparticlebinderBlock;
import net.mcreator.creativeworld.block.SolarpanelBlock;
import net.mcreator.creativeworld.block.RsinlogwithresinBlock;
import net.mcreator.creativeworld.block.ResintreesaplingBlock;
import net.mcreator.creativeworld.block.ResinWoodBlock;
import net.mcreator.creativeworld.block.ResinStairsBlock;
import net.mcreator.creativeworld.block.ResinSlabBlock;
import net.mcreator.creativeworld.block.ResinPlanksBlock;
import net.mcreator.creativeworld.block.ResinLogBlock;
import net.mcreator.creativeworld.block.ResinLeavesBlock;
import net.mcreator.creativeworld.block.ResinFenceGateBlock;
import net.mcreator.creativeworld.block.ResinFenceBlock;
import net.mcreator.creativeworld.block.QuantumteleporterblockBlock;
import net.mcreator.creativeworld.block.Quantumteleporterblock2Block;
import net.mcreator.creativeworld.block.MachinecaseBlock;
import net.mcreator.creativeworld.block.InsulatedCopperWireBlock;
import net.mcreator.creativeworld.block.InfinityenergyBlock;
import net.mcreator.creativeworld.block.FanBlock;
import net.mcreator.creativeworld.block.CrusherBlock;
import net.mcreator.creativeworld.block.CreativiumOreBlock;
import net.mcreator.creativeworld.block.CreativiumBlockBlock;
import net.mcreator.creativeworld.block.CopperWireBlock;
import net.mcreator.creativeworld.block.CoalgeneratorBlock;
import net.mcreator.creativeworld.block.Coalgenerator1Block;
import net.mcreator.creativeworld.block.BronzeBlockBlock;
import net.mcreator.creativeworld.block.BatteryblockBlock;
import net.mcreator.creativeworld.block.BUGBlock;
import net.mcreator.creativeworld.block.AdvencedsolarpanelBlock;
import net.mcreator.creativeworld.block.AdvencedmachinecaseBlock;
import net.mcreator.creativeworld.block.AccumulatiumOreBlock;
import net.mcreator.creativeworld.block.AccumulatiumBlockBlock;
import net.mcreator.creativeworld.CreativeWorldMod;

public class CreativeWorldModBlocks {
	public static Block COPPER_WIRE;
	public static Block INSULATED_COPPER_WIRE;
	public static Block TIN_ORE;
	public static Block TITAN_ORE;
	public static Block ACCUMULATIUM_ORE;
	public static Block CREATIVIUM_ORE;
	public static Block TIN_BLOCK;
	public static Block BRONZE_BLOCK;
	public static Block ACCUMULATIUM_BLOCK;
	public static Block CREATIVIUM_BLOCK;
	public static Block RESIN_LOG;
	public static Block RSINLOGWITHRESIN;
	public static Block RESIN_WOOD;
	public static Block RESIN_PLANKS;
	public static Block RESIN_STAIRS;
	public static Block RESIN_SLAB;
	public static Block RESIN_LEAVES;
	public static Block RESIN_FENCE;
	public static Block RESIN_FENCE_GATE;
	public static Block TITAN_BLOCK;
	public static Block MACHINECASE;
	public static Block COALGENERATOR;
	public static Block CRUSHER;
	public static Block FAN;
	public static Block BATTERYBLOCK;
	public static Block SOLARPANEL;
	public static Block ADVENCEDMACHINECASE;
	public static Block ADVENCEDSOLARPANEL;
	public static Block INFINITYENERGY;
	public static Block QUANTUMTELEPORTERBLOCK;
	public static Block QUANTUMTELEPORTERBLOCK_2;
	public static Block STATIONARYPARTICLEBINDER;
	public static Block RESINTREESAPLING;
	public static Block COALGENERATOR_1;
	public static Block BUG;

	public static void load() {
		COPPER_WIRE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "copper_wire"), new CopperWireBlock());
		INSULATED_COPPER_WIRE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "insulated_copper_wire"), new InsulatedCopperWireBlock());
		TIN_ORE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "tin_ore"), new TinOreBlock());
		TITAN_ORE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "titan_ore"), new TitanOreBlock());
		ACCUMULATIUM_ORE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "accumulatium_ore"), new AccumulatiumOreBlock());
		CREATIVIUM_ORE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "creativium_ore"), new CreativiumOreBlock());
		TIN_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "tin_block"), new TinBlockBlock());
		BRONZE_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "bronze_block"), new BronzeBlockBlock());
		ACCUMULATIUM_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "accumulatium_block"), new AccumulatiumBlockBlock());
		CREATIVIUM_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "creativium_block"), new CreativiumBlockBlock());
		RESIN_LOG = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resin_log"), new ResinLogBlock());
		RSINLOGWITHRESIN = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "rsinlogwithresin"), new RsinlogwithresinBlock());
		RESIN_WOOD = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resin_wood"), new ResinWoodBlock());
		RESIN_PLANKS = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resin_planks"), new ResinPlanksBlock());
		RESIN_STAIRS = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resin_stairs"), new ResinStairsBlock());
		RESIN_SLAB = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resin_slab"), new ResinSlabBlock());
		RESIN_LEAVES = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resin_leaves"), new ResinLeavesBlock());
		RESIN_FENCE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resin_fence"), new ResinFenceBlock());
		RESIN_FENCE_GATE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resin_fence_gate"), new ResinFenceGateBlock());
		TITAN_BLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "titan_block"), new TitanBlockBlock());
		MACHINECASE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "machinecase"), new MachinecaseBlock());
		COALGENERATOR = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "coalgenerator"), new CoalgeneratorBlock());
		CRUSHER = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "crusher"), new CrusherBlock());
		FAN = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "fan"), new FanBlock());
		BATTERYBLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "batteryblock"), new BatteryblockBlock());
		SOLARPANEL = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "solarpanel"), new SolarpanelBlock());
		ADVENCEDMACHINECASE = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "advencedmachinecase"), new AdvencedmachinecaseBlock());
		ADVENCEDSOLARPANEL = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "advencedsolarpanel"), new AdvencedsolarpanelBlock());
		INFINITYENERGY = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "infinityenergy"), new InfinityenergyBlock());
		QUANTUMTELEPORTERBLOCK = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "quantumteleporterblock"), new QuantumteleporterblockBlock());
		QUANTUMTELEPORTERBLOCK_2 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "quantumteleporterblock_2"), new Quantumteleporterblock2Block());
		STATIONARYPARTICLEBINDER = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "stationaryparticlebinder"), new StationaryparticlebinderBlock());
		RESINTREESAPLING = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "resintreesapling"), new ResintreesaplingBlock());
		COALGENERATOR_1 = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "coalgenerator_1"), new Coalgenerator1Block());
		BUG = Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(CreativeWorldMod.MODID, "bug"), new BUGBlock());
	}

	public static void clientLoad() {
		CopperWireBlock.clientInit();
		InsulatedCopperWireBlock.clientInit();
		TinOreBlock.clientInit();
		TitanOreBlock.clientInit();
		AccumulatiumOreBlock.clientInit();
		CreativiumOreBlock.clientInit();
		TinBlockBlock.clientInit();
		BronzeBlockBlock.clientInit();
		AccumulatiumBlockBlock.clientInit();
		CreativiumBlockBlock.clientInit();
		ResinLogBlock.clientInit();
		RsinlogwithresinBlock.clientInit();
		ResinWoodBlock.clientInit();
		ResinPlanksBlock.clientInit();
		ResinStairsBlock.clientInit();
		ResinSlabBlock.clientInit();
		ResinLeavesBlock.clientInit();
		ResinFenceBlock.clientInit();
		ResinFenceGateBlock.clientInit();
		TitanBlockBlock.clientInit();
		MachinecaseBlock.clientInit();
		CoalgeneratorBlock.clientInit();
		CrusherBlock.clientInit();
		FanBlock.clientInit();
		BatteryblockBlock.clientInit();
		SolarpanelBlock.clientInit();
		AdvencedmachinecaseBlock.clientInit();
		AdvencedsolarpanelBlock.clientInit();
		InfinityenergyBlock.clientInit();
		QuantumteleporterblockBlock.clientInit();
		Quantumteleporterblock2Block.clientInit();
		StationaryparticlebinderBlock.clientInit();
		ResintreesaplingBlock.clientInit();
		Coalgenerator1Block.clientInit();
		BUGBlock.clientInit();
	}
}
